services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Account\:
    resource: 'src/*'
    exclude: 'src/**/DataType'
    public: true

  OxidEsales\GraphQL\Account\Shared\Service\NamespaceMapper:
      class: OxidEsales\GraphQL\Account\Shared\Service\NamespaceMapper
      tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Account\Shared\Service\PermissionProvider:
      class: OxidEsales\GraphQL\Account\Shared\Service\PermissionProvider
      tags: ['graphql_permission_provider']
